name: Build DeathMessages

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

      - name: Upload DeathMessages DevBuild
        if: github.ref_name == 'master' && github.event_name != 'pull_request'
        # TODO: Update release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: "DeathMessages v1.5.0-SNAPSHOT"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            DeathMessagesLegacy/build/libs/DeathMessages-*.jar
            DeathMessagesModern/build/libs/DeathMessages-*.jar
          prerelease: true

      - name: Upload DeathMessages Legacy Nightly
        if: github.ref_name == 'dev'
        uses: actions/upload-artifact@v7
        with:
          path: DeathMessagesLegacy/build/libs/DeathMessages-*.jar
          archive: false

      - name: Upload DeathMessages Modern Nightly
        if: github.ref_name == 'dev'
        uses: actions/upload-artifact@v7
        with:
          path: DeathMessagesModern/build/libs/DeathMessages-*.jar
          archive: false
