name: Build DeathMessages
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: zulu

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build --stacktrace

      - name: Upload DeathMessages DevBuild
        if: github.ref_name == 'master' && github.event_name != 'pull_request'
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "DeathMessages v1.4.19-SNAPSHOT"
          automatic_release_tag: "dev-build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/DeathMessages-*.jar"
          prerelease: true

      - name: Upload DeathMessages Nightly
        if: github.ref_name == 'dev'
        uses: actions/upload-artifact@main
        with:
          name: DeathMessages-Nightly
          path: build/libs/DeathMessages-*.jar
